### ISSUE TITLE
[CHORE] Separate the CSS and JS

### ISSUE THREAD

**Issue by KendallDoesCoding** [Kendall-Does-Coding-Websites/todays-date#1]
Create new files for CSS and Javascript and link it back into the HTML. 

Name the css file - `styles.css` and Javascript file `index.html`

To link css in HTML add this after the `<head>` tag:
```
  <link rel="stylesheet" href="styles.css">
```

To link JS in HTML add this after the `</body>` tag
```
<script src="index.js"> </script>
```

**Comment by keshav97-git** [comment]
hey i am done with my first issue but i dont know how i push it here

**Comment by KendallDoesCoding** [comment]
#2 is already made by @kumarvivek, so going ahead with that. @kumarvivek, @keshav97-git , in future- please req to be assigned to issue before starting work, once assigned then only begin working on the issue.

**Comment by KendallDoesCoding** [comment]
done in #2
