### ISSUE TITLE
[FEAT] Add a gradient background which looks nice.

### ISSUE THREAD

**Issue by KendallDoesCoding** [Kendall-Does-Coding-Websites/todays-date#3]
Add a nice gradient background to make the page look vibrant.

**Comment by ashutosh-rath02** [comment]
@KendallDoesCoding Can I work on it?

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding Can I work on it?

Sure!

**Comment by ashutosh-rath02** [comment]
@KendallDoesCoding Do you want a linear-gradient or simple background colour?

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding Do you want a linear-gradient or simple background colour?

Whatever you think looks the best, something like on https://chatgpt-website.kendalldoescoding.tech/ would be my preference though.
